# Crimson Flame (Kitty Theme Match)
name = Crimson Flame

background = #25090a
foreground = #ebdada
cursor = #e32a10
cursor_text = #25090a
selection_bg = #cf2824
selection_fg = #ffffff

# Tab Bar
active_tab_bg = #cf2824
active_tab_fg = #ffffff
inactive_tab_bg = #360e10
inactive_tab_fg = #b58487
tab_bar_bg = #1a0506

# 16 ANSI Colors
color0 = #330d0f
color1 = #cf2824
color2 = #e0682b
color3 = #e6ab3c
color4 = #ff7373
color5 = #bd5486
color6 = #ff9f68
color7 = #cfbebe
color8 = #6e282c
color9 = #e32a10
color10 = #ff843d
color11 = #ffc85a
color12 = #ffa19c
color13 = #de6ea4
color14 = #ffbe94
color15 = #faecec
